# Generated by Django 5.1.2 on 2024-11-10 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('weather', models.IntegerField()),
                ('acc_hotel', models.BooleanField(default=False)),
                ('acc_hostel', models.BooleanField(default=False)),
                ('acc_guesthouse', models.BooleanField(default=False)),
                ('acc_agrotourism', models.BooleanField(default=False)),
                ('acc_camping', models.BooleanField(default=False)),
                ('acc_airbnb', models.BooleanField(default=False)),
                ('land_mountains', models.BooleanField(default=False)),
                ('land_sea', models.BooleanField(default=False)),
                ('land_lake', models.BooleanField(default=False)),
                ('land_city', models.BooleanField(default=False)),
                ('act_water', models.BooleanField(default=False)),
                ('act_sightseeing', models.BooleanField(default=False)),
                ('act_museums', models.BooleanField(default=False)),
                ('act_nightlife', models.BooleanField(default=False)),
                ('act_beach', models.BooleanField(default=False)),
                ('act_nature', models.BooleanField(default=False)),
                ('act_sports', models.BooleanField(default=False)),
                ('cuisine', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
