# Generated by Django 5.1.2 on 2024-11-10 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserResponse',
        ),
    ]
