# Generated by Django 4.2.16 on 2025-05-10 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_place_userlike'),
    ]

    operations = [
    ]
