# Generated by Django 4.2.16 on 2025-05-10 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_place_userlike'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userlike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userlike',
            name='place',
        ),
        migrations.RemoveField(
            model_name='userlike',
            name='user',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='UserLike',
        ),
    ]
